-- ==========================================
-- BASIC QUERIES
-- ==========================================

-- 1. Display all customers
SELECT * FROM customers;

-- 2. Display all products
SELECT * FROM products;

-- 3. Display all orders
SELECT * FROM orders;

-- 4. Display all order items
SELECT * FROM order_items;

-- 5. Show first name, last name and city of customers
SELECT first_name, last_name, city FROM customers;

-- 6. Display products with unit price greater than 50000
SELECT * FROM products WHERE unit_price > 50000;

-- 7. Display delivered orders
SELECT * FROM orders WHERE order_status = 'Delivered';

-- 8. Display customers from Maharashtra
SELECT * FROM customers
WHERE state = 'Maharashtra';

-- 9. Display products sorted by price (highest first)
SELECT * FROM products
ORDER BY unit_price DESC;

-- 10. Display latest orders
SELECT * FROM orders
ORDER BY order_date DESC;

-- ==========================================
-- AGGREGATE FUNCTIONS
-- ==========================================

-- 11. Total number of customers
SELECT COUNT(*) AS total_customers
FROM customers;

-- 12. Total number of products
SELECT COUNT(*) AS total_products
FROM products;

-- 13. Total number of orders
SELECT COUNT(*) AS total_orders
FROM orders;

-- 14. Total number of order items
SELECT COUNT(*) AS total_order_items
FROM order_items;

-- 15. Total revenue generated
SELECT SUM(total_amount) AS total_revenue
FROM orders;

-- 16. Average order value
SELECT ROUND(AVG(total_amount), 2) AS average_order_value
FROM orders;

-- 17. Most expensive product
SELECT MAX(unit_price) AS highest_price
FROM products;

-- 18. Cheapest product
SELECT MIN(unit_price) AS lowest_price
FROM products;

-- 19. Total stock available
SELECT SUM(stock_quantity) AS total_stock
FROM products;

-- 20. Average product price
SELECT ROUND(AVG(unit_price), 2) AS average_product_price
FROM products;

-- ==========================================
-- GROUP BY & HAVING
-- ==========================================

-- 21. Number of customers in each state
SELECT state,
       COUNT(*) AS total_customers
FROM customers
GROUP BY state
ORDER BY total_customers DESC;

-- 22. Number of customers in each city
SELECT city,
       COUNT(*) AS total_customers
FROM customers
GROUP BY city
ORDER BY total_customers DESC;

-- 23. Number of products in each category
SELECT category,
       COUNT(*) AS total_products
FROM products
GROUP BY category
ORDER BY total_products DESC;

-- 24. Average product price by category
SELECT category,
       ROUND(AVG(unit_price),2) AS average_price
FROM products
GROUP BY category
ORDER BY average_price DESC;

-- 25. Total stock by category
SELECT category,
       SUM(stock_quantity) AS total_stock
FROM products
GROUP BY category
ORDER BY total_stock DESC;

-- 26. Number of orders by status
SELECT order_status,
       COUNT(*) AS total_orders
FROM orders
GROUP BY order_status
ORDER BY total_orders DESC;

-- 27. Revenue by order status
SELECT order_status,
       ROUND(SUM(total_amount),2) AS revenue
FROM orders
GROUP BY order_status
ORDER BY revenue DESC;

-- 28. States having more than 20 customers
SELECT state,
       COUNT(*) AS total_customers
FROM customers
GROUP BY state
HAVING COUNT(*) > 20
ORDER BY total_customers DESC;

-- 29. Categories having average price greater than 20000
SELECT category,
       ROUND(AVG(unit_price),2) AS average_price
FROM products
GROUP BY category
HAVING AVG(unit_price) > 20000
ORDER BY average_price DESC;

-- 30. Order status having more than 100 orders
SELECT order_status,
       COUNT(*) AS total_orders
FROM orders
GROUP BY order_status
HAVING COUNT(*) > 100
ORDER BY total_orders DESC;

-- ==========================================
-- JOINS
-- ==========================================

-- 31. Display customer names with their orders
SELECT c.customer_id,
       CONCAT(c.first_name, ' ', c.last_name) AS customer_name,
       o.order_id,
       o.order_date,
       o.total_amount
FROM customers c
INNER JOIN orders o
ON c.customer_id = o.customer_id;

-- 32. Display order details with product names
SELECT oi.order_item_id,
       oi.order_id,
       p.product_name,
       oi.quantity,
       oi.selling_price
FROM order_items oi
INNER JOIN products p
ON oi.product_id = p.product_id;

-- 33. Display customer names and total number of orders
SELECT c.customer_id,
       CONCAT(c.first_name, ' ', c.last_name) AS customer_name,
       COUNT(o.order_id) AS total_orders
FROM customers c
LEFT JOIN orders o
ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.first_name, c.last_name
ORDER BY total_orders DESC;

-- 34. Top 10 customers by total spending
SELECT c.customer_id,
       CONCAT(c.first_name, ' ', c.last_name) AS customer_name,
       ROUND(SUM(o.total_amount),2) AS total_spent
FROM customers c
INNER JOIN orders o
ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.first_name, c.last_name
ORDER BY total_spent DESC
LIMIT 10;

-- 35. Revenue generated by each category
SELECT p.category,
       ROUND(SUM(oi.quantity * oi.selling_price),2) AS revenue
FROM products p
INNER JOIN order_items oi
ON p.product_id = oi.product_id
GROUP BY p.category
ORDER BY revenue DESC;

-- 36. Top 10 best-selling products
SELECT p.product_name,
       SUM(oi.quantity) AS total_quantity_sold
FROM products p
INNER JOIN order_items oi
ON p.product_id = oi.product_id
GROUP BY p.product_name
ORDER BY total_quantity_sold DESC
LIMIT 10;

-- 37. Products that have never been ordered
SELECT p.product_id,
       p.product_name
FROM products p
LEFT JOIN order_items oi
ON p.product_id = oi.product_id
WHERE oi.product_id IS NULL;

-- 38. Customers who have never placed an order
SELECT c.customer_id,
       CONCAT(c.first_name,' ',c.last_name) AS customer_name
FROM customers c
LEFT JOIN orders o
ON c.customer_id = o.customer_id
WHERE o.customer_id IS NULL;

-- 39. Total revenue generated by each customer
SELECT c.customer_id,
       CONCAT(c.first_name,' ',c.last_name) AS customer_name,
       ROUND(SUM(o.total_amount),2) AS revenue
FROM customers c
INNER JOIN orders o
ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.first_name, c.last_name
ORDER BY revenue DESC;

-- 40. Number of products sold by category
SELECT p.category,
       SUM(oi.quantity) AS products_sold
FROM products p
INNER JOIN order_items oi
ON p.product_id = oi.product_id
GROUP BY p.category
ORDER BY products_sold DESC;

-- ==========================================
-- SUBQUERIES
-- ==========================================

-- 41. Customers who have spent more than the average customer spending
SELECT customer_id,
       customer_name,
       total_spent
FROM
(
    SELECT c.customer_id,
           CONCAT(c.first_name,' ',c.last_name) AS customer_name,
           SUM(o.total_amount) AS total_spent
    FROM customers c
    JOIN orders o
        ON c.customer_id = o.customer_id
    GROUP BY c.customer_id, c.first_name, c.last_name
) customer_sales
WHERE total_spent >
(
    SELECT AVG(total_spent)
    FROM
    (
        SELECT SUM(total_amount) AS total_spent
        FROM orders
        GROUP BY customer_id
    ) avg_sales
);

-- 42. Products priced above the average product price
SELECT *
FROM products
WHERE unit_price >
(
    SELECT AVG(unit_price)
    FROM products
);

-- 43. Orders having total amount greater than average order amount
SELECT *
FROM orders
WHERE total_amount >
(
    SELECT AVG(total_amount)
    FROM orders
);

-- 44. Customers who placed the maximum number of orders
SELECT customer_id,
       COUNT(*) AS total_orders
FROM orders
GROUP BY customer_id
HAVING COUNT(*) =
(
    SELECT MAX(order_count)
    FROM
    (
        SELECT COUNT(*) AS order_count
        FROM orders
        GROUP BY customer_id
    ) x
);

-- 45. Products never sold
SELECT product_name
FROM products
WHERE product_id NOT IN
(
    SELECT DISTINCT product_id
    FROM order_items
);

-- ==========================================
-- COMMON TABLE EXPRESSIONS (CTEs)
-- ==========================================

-- 46. Top 10 customers by total spending
WITH customer_sales AS
(
    SELECT
        c.customer_id,
        CONCAT(c.first_name, ' ', c.last_name) AS customer_name,
        SUM(o.total_amount) AS total_spent
    FROM customers c
    JOIN orders o
        ON c.customer_id = o.customer_id
    GROUP BY c.customer_id, c.first_name, c.last_name
)
SELECT *
FROM customer_sales
ORDER BY total_spent DESC
LIMIT 10;

-- 47. Revenue by category
WITH category_sales AS
(
    SELECT
        p.category,
        SUM(oi.quantity * oi.selling_price) AS revenue
    FROM products p
    JOIN order_items oi
        ON p.product_id = oi.product_id
    GROUP BY p.category
)
SELECT *
FROM category_sales
ORDER BY revenue DESC;

-- 48. Customers with more than 5 orders
WITH customer_orders AS
(
    SELECT
        customer_id,
        COUNT(*) AS total_orders
    FROM orders
    GROUP BY customer_id
)
SELECT *
FROM customer_orders
WHERE total_orders > 5
ORDER BY total_orders DESC;

-- 49. Average revenue generated per customer
WITH customer_revenue AS
(
    SELECT
        customer_id,
        SUM(total_amount) AS revenue
    FROM orders
    GROUP BY customer_id
)
SELECT
    ROUND(AVG(revenue),2) AS average_customer_revenue
FROM customer_revenue;

-- 50. Categories having revenue above average category revenue
WITH category_revenue AS
(
    SELECT
        p.category,
        SUM(oi.quantity * oi.selling_price) AS revenue
    FROM products p
    JOIN order_items oi
        ON p.product_id = oi.product_id
    GROUP BY p.category
)
SELECT *
FROM category_revenue
WHERE revenue >
(
    SELECT AVG(revenue)
    FROM category_revenue
)
ORDER BY revenue DESC;

-- ==========================================
-- WINDOW FUNCTIONS
-- ==========================================

-- 51. Rank customers based on total spending
SELECT
    customer_id,
    ROUND(SUM(total_amount),2) AS total_spent,
    RANK() OVER(ORDER BY SUM(total_amount) DESC) AS customer_rank
FROM orders
GROUP BY customer_id;

-- 52. Dense rank customers by spending
SELECT
    customer_id,
    ROUND(SUM(total_amount),2) AS total_spent,
    DENSE_RANK() OVER(ORDER BY SUM(total_amount) DESC) AS dense_customer_rank
FROM orders
GROUP BY customer_id;

-- 53. Row number for products based on price
SELECT
    product_name,
    category,
    unit_price,
    ROW_NUMBER() OVER(ORDER BY unit_price DESC) AS row_num
FROM products;

-- 54. Rank products within each category by price
SELECT
    product_name,
    category,
    unit_price,
    RANK() OVER(
        PARTITION BY category
        ORDER BY unit_price DESC
    ) AS category_rank
FROM products;

-- 55. Running revenue by order date
SELECT
    order_date,
    total_amount,
    SUM(total_amount)
    OVER(
        ORDER BY order_date
    ) AS running_revenue
FROM orders;

-- 56. Previous order amount using LAG()
SELECT
    order_id,
    order_date,
    total_amount,
    LAG(total_amount)
    OVER(ORDER BY order_date) AS previous_order_amount
FROM orders;

-- 57. Next order amount using LEAD()
SELECT
    order_id,
    order_date,
    total_amount,
    LEAD(total_amount)
    OVER(ORDER BY order_date) AS next_order_amount
FROM orders;

-- 58. Average order amount by customer
SELECT
    customer_id,
    order_id,
    total_amount,
    ROUND(
        AVG(total_amount)
        OVER(PARTITION BY customer_id),2
    ) AS avg_customer_order
FROM orders;

-- 59. Highest priced product in each category
SELECT *
FROM
(
    SELECT
        product_name,
        category,
        unit_price,
        ROW_NUMBER() OVER(
            PARTITION BY category
            ORDER BY unit_price DESC
        ) AS rn
    FROM products
) t
WHERE rn = 1;

-- 60. Top 3 customers by spending
SELECT *
FROM
(
    SELECT
        customer_id,
        ROUND(SUM(total_amount),2) AS total_spent,
        DENSE_RANK() OVER(
            ORDER BY SUM(total_amount) DESC
        ) AS rnk
    FROM orders
    GROUP BY customer_id
) t
WHERE rnk <= 3;